# Page settings
baseurl = "https://www.pixiesfaces.com"
title = "Pixies Face Painting"
disableKinds = ["taxonomy","term","RSS"]
enableRobotsTXT = true
canonifyURLs = true

# Google Analytics Tag
googleAnalytics = "G-9GQ5TF9022"

# Language Settings
languageCode = "en-us"
DefaultContentLanguage = "en"
[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = "0.5"

[params]
  # SEO Related Config
  author = "Jenny Saunders"
  description = "Pixies Face Painting|Beautiful faces, balloons and fairy parties"
  email = "info@pixiesfaces.com"
  github = "https://github.com/pixiesfaces"
  seoimage = "/images/background-logo.png"
  twitter = "@pixiesfaces"
  site_type = "LocalBusiness"
  local_business_type = "EntertainmentBusiness"
  favicon = "favicon.png"

  # Main Colours
  backgroundColor = "#fff"
  whiteColor = "#fff"
  textColor = "#3d2b3d"
  highlightColor = "#9900f6" 

  # Nav Toggle
  navbarHeight = "50px"
  navbarToggleTopPadding = "8px"
  navToggleColor = "#3d2b3d"
  barThickness = "4px"
  burgerWidth = "40px"
  spacing = "-12px"
  spacingActive = "-15px"

  # Gradient Home/Hero Section
  homeColor1 = "#f00"
  homeColor2 = "#f0f"

  # Gradient Instagram Section
  instaColor1 = "#f0f"
  instaColor2 = "#00f"

  # Gradient work/Gallery Section
  workColor1 = "#f0f"
  workColor2 = "#00f"

  # Gradient testimonial Section
  testimonialColor1 = "#00f"
  testimonialColor2 = "#f0f"

  # Gradient services/Bookings Section
  servicesColor1 = "#00f"
  servicesColor2 = "#0f0"

  # Default body text size
  bodyTextSize = "18px"
  
  # Menu item Text size
  menuTextSize = "22px"
  toggleMenuTextSize = "22px"
 
  # Background Header Section
  # icon size should be about 2/3 of button size
  # offset should be negative half button size
  gotoSectionIconSize = "33px"
  gotoSectionButtonSize = "50px"
  gotoSectionButtonOffset = "-25px"
  gotoSectionIconColour = "#3d2b3d"

  # Hero image text sizes
  heroTextSizeH1 = "60px"
  heroTextSizeH2 = "28px"

  # Intro section text sizes
  introIconSize = "50px"
  introTextSizeH2 = "24px"
  introTextSize = "16px"

  # General section headings text sizes
  sectionHeadingTextSizeH2 = "50px"
  sectionHeadingTextSizeH2Mobile = "30px"
  sectionHeadingTextSizeH3 = "28px"
  sectionHeadingTextSizeH3Mobile = "24px"

  # Gallery section text sizes
  workItemTextSizeH2 = "18px"
  # Gallery - not used
  workItemTextSizeSpan = "16px"

  # Testimonal section text sizes
  testimonialIconSize = "50px"
  testimonialTextSize = "18px"
  testimonialAuthorTextSize = "16px"

  # Services section text sizes
  servicesIconSize = "70px"
  servicesTextSizeH3 = "24px"
  servicesTextSize = "18px"

  # Contact section text sizes
  formTextSize = "18px"

  # Footer text sizes
  socialIconSize = "16px"
  copyrightTextSize = "14px"

  # Error text sizes
  pixiesErrorTextSizeH1 = "50px"
  pixiesErrorTextSizeH2 = "28px"

  # Gradient Error Section
  errorColor1 = "#f00"
  errorColor2 = "#f0f"

  # Navigation
  [params.navigation]
    showlogo = true
    img = "banner-logo.png"
    logoheight = "50px"
    logowidth = "50px"
    alt = "Pixies Logo"

    # Menu Configuration
    home = "Intro"
    insta = "Gallery"
    work = "Gallery"
    testimonials = "Testimonials"
    services = "Booking Info"
    contact = "Contact"

  [params.navigation.social]
    enable = true
    links = [
        ["fa-brands fa-instagram", "https://instagram.com/pixiesfacepainting"]
      ]

  # Fixed Background section
  [params.background]
    enableheader = true  
    enablefooter = false  
    image = "background-logo.png"
    alt = "Pixies Logo"

  # Hero section
  [params.hero]
    title = "Pixies Face Painting"
    subtitle = 'Beautiful face painting, balloon twisting and fairy parties in Melbourne East.'
    image = "redtiger.png"
    alt = "Pixies Logo"

  # Intro section
  # Font awesome icons https://fontawesome.com/icons
  [params.intro]
  enable = false

  [[params.intro.item]]
    title = "Face Painting"
    description = "Your childern will go mad for these faces!"
    navigation = "testimonials"
    button = "What People Say"
    icon = "fa-solid fa-comments"
    img = "snowtiger.png"
    alt = "Alt Text"

  [[params.intro.item]]
    title = "Balloons"
    description = "Amazing balloons, the like of which you've never seen."
    navigation = "work"
    button = "See For Yourself"
    icon = "fa-solid fa-images"
    img = "iceprincess.png"
    alt = "Alt Text"

  [[params.intro.item]]
    title = "Fairy Parties"
    description = "You won't believe how fun Pixies parties can be!"
    navigation = "services"
    button = "Booking Info"
    icon = "fa-solid fa-face-smile-beam"
    img = "flowers.png"
    alt = "Alt Text"

  # Instagram Feed section
  [params.insta]
    enable = false
    title = "Gallery"
    description = "Beautiful creations from Instagram"
    footertext = '&copy; Pixies Face Painting 2025'

  # Work section
  [params.work]
    enable = true
    title = "Gallery"
    description = "Beautiful creations from Instagram"
    footertext = '&copy; Pixies Face Painting 2025'

    [[params.work.row]]
      img = "instagram-1.jpg"
      alt = "Instagram Image 1"

    [[params.work.row]]
      img = "instagram-2.jpg"
      alt = "Instagram Image 2"

    [[params.work.row]]
      img = "instagram-3.jpg"
      alt = "Instagram Image 3"

    [[params.work.row]]
      img = "instagram-4.jpg"
      alt = "Instagram Image 4"

    [[params.work.row]]
      img = "instagram-5.jpg"
      alt = "Instagram Image 5"

    [[params.work.row]]
      img = "instagram-6.jpg"
      alt = "Instagram Image 6"

    [[params.work.row]]
      img = "instagram-7.jpg"
      alt = "Instagram Image 7"

    [[params.work.row]]
      img = "instagram-8.jpg"
      alt = "Instagram Image 8"

    [[params.work.row]]
      img = "instagram-9.jpg"
      alt = "Instagram Image 9"

    [[params.work.row]]
      img = "instagram-10.jpg"
      alt = "Instagram Image 10"

    [[params.work.row]]
      img = "instagram-11.jpg"
      alt = "Instagram Image 11"

    [[params.work.row]]
      img = "instagram-12.jpg"
      alt = "Instagram Image 12"

    [[params.work.row]]
      img = "instagram-13.jpg"
      alt = "Instagram Image 13"

    [[params.work.row]]
      img = "instagram-14.jpg"
      alt = "Instagram Image 14"

    [[params.work.row]]
      img = "instagram-15.jpg"
      alt = "Instagram Image 15"

    [[params.work.row]]
      img = "instagram-16.jpg"
      alt = "Instagram Image 16"

    [[params.work.row]]
      img = "instagram-17.jpg"
      alt = "Instagram Image 17"

    [[params.work.row]]
      img = "instagram-18.jpg"
      alt = "Instagram Image 18"

    [[params.work.row]]
      img = "instagram-19.jpg"
      alt = "Instagram Image 19"

    [[params.work.row]]
      img = "instagram-20.jpg"
      alt = "Instagram Image 20"

    [[params.work.row]]
      img = "instagram-21.jpg"
      alt = "Instagram Image 21"

    [[params.work.row]]
      img = "instagram-22.jpg"
      alt = "Instagram Image 22"

    [[params.work.row]]
      img = "instagram-23.jpg"
      alt = "Instagram Image 23"

    [[params.work.row]]
      img = "instagram-24.jpg"
      alt = "Instagram Image 24"

    [[params.work.row]]
      img = "instagram-25.jpg"
      alt = "Instagram Image 25"

    [[params.work.row]]
      img = "iceprincess.png"
      alt = "Ice Princess"

    [[params.work.row]]
      img = "irridescentbutterfly.png"
      alt = "Irridescent Butterfly"

    [[params.work.row]]
      img = "redtiger.png"
      alt = "Red Tiger"

    [[params.work.row]]
      img = "snaketiger.png"
      alt = "Snake Tiger"

   [[params.work.row]]
      img = "flowerprincess.png"
      alt = "Flower Princess"

   [[params.work.row]]
      img = "flowers.png"
      alt = "Flowers"

   [[params.work.row]]
      img = "happydog.png"
      alt = "Happy Dog"

    [[params.work.row]]
      img = "snowtiger.png"
      alt = "Snow Tiger"

    [[params.work.row]]
      img = "illusion.png"
      alt = "Illusion Magazine"

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "Testimonials"
    description = "People love Pixie!"

    [[params.testimonials.item]]
      quote = "&ldquo;My daughter had the best time&rdquo;"
      person = 'Sarah McDermott'
      icon = "fa-solid fa-user"

    [[params.testimonials.item]]
      quote = "&ldquo;Pixie is amazing.  She made my daughter's day so special!&rdquo;"
      person = 'Mary Smith'
      icon = "fa-solid fa-user"

    [[params.testimonials.item]]
      quote = "&ldquo;Always a professional, we hire Pixie every year!&rdquo;"
      person = 'Bob Harris'
      icon = "fa-regular fa-user"
    
  # Services section
  # Font awesome icons https://fontawesome.com/icons
  [params.services]
    enable = false
    title = "Booking Information"
    description = "put your sub heading here"

    [[params.services.item]]
      title = "Face Painting"
      description = "put your description here"
      icon = "fa-solid fa-paintbrush"

    [[params.services.item]]
      title = "Ballooning"
      description = "put your description here"
      icon = "fa-solid fa-face-smile"

    [[params.services.item]]
      title = "Fairy Parties"
      description = "put your description here"
      icon = "fa-solid fa-cake-candles"

  # Contact section
  [params.contact]
    enable = true
    form = false
    title = "Contact"
    #description = "Get in touch for more information about face painting, balloon twisting and fairy parties in Melbourne East."
    description = "Unfortunately Pixies is no longer taking bookings."
    info = "Call or Message"
    formHeader = "Enquire by Email"
    
    # Font awesome icons https://fontawesome.com/icons
    details = [
        ["fa-solid fa-phone", "tel:+61406074909", "0406 074 909"],
        ["fa-solid fa-envelope", "mailto:info@pixiesfaces.com", "info@pixiesfaces.com"]
      ]
    
    # Form Labels
    email = "Your email address"
    phone = "Best contact number"
    subject = "Email subject"
    message = "Email message"
    location = "Event suburb"
    button = "Send email"

  # Footer section
  # Font awesome icons https://fontawesome.com/icons
  [params.footer]
    enable = true
    copyright = '&copy; Pixies Face Painting 2025'
    links = [
        ["fa-brands fa-instagram", "https://instagram.com/pixiesfacepainting"]
      ]

  # Custom error/404 page
  [params.errorpage]
    image = "redtiger.png"
    alt = "Red Tiger"
    title = "Sorry"
    subtitle = "It seems that page does not exist"
    button = "Back to Home"